"""Initial Migration

Revision ID: 9d1fa8599292
Revises: 
Create Date: 2025-08-02 14:39:47.104142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d1fa8599292'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=155), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=155), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='content_scheduler')

    op.create_table('type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='content_scheduler')

    op.create_table('scheduled_time',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='content_scheduler')

    op.create_table('platform',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='content_scheduler')

    op.create_table('interaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interaction', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='content_scheduler')
    
    op.create_table('media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_time_id', sa.BigInteger(), nullable=True),
    sa.Column('type_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['scheduled_time_id'], ['content_scheduler.scheduled_time.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['content_scheduler.type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['content_scheduler.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content_scheduler')

    op.create_table('media_platform',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_status', sa.Enum('DRAFT', 'SCHEDULED', 'POSTED', 'CANCELLED', 'REJECTED', 'FAILED', name='post_status', schema='content_scheduler'), nullable=True),
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('platform_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['content_scheduler.media.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['content_scheduler.platform.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content_scheduler')

    op.create_table('media_interaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('interaction_id', sa.BigInteger(), nullable=False),
    sa.Column('media_platform_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['content_scheduler.interaction.id'], ),
    sa.ForeignKeyConstraint(['media_platform_id'], ['content_scheduler.media_platform.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='content_scheduler') 

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user', schema='content_scheduler')
    op.drop_table('type', schema='content_scheduler')
    op.drop_table('scheduled_time', schema='content_scheduler')
    op.drop_table('platform', schema='content_scheduler')
    op.drop_table('interaction', schema='content_scheduler')
    op.drop_table('media', schema='content_scheduler')
    op.drop_table('media_platform', schema='content_scheduler')
    op.drop_table('media_interaction', schema='content_scheduler')
    # ### end Alembic commands ###
